// <auto-generated />
namespace Broadway._630.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialSetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialSetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202107050114377_initialSetup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
