// <auto-generated />
namespace Broadway._630.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedSTudent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedSTudent));
        
        string IMigrationMetadata.Id
        {
            get { return "202107070109438_updatedSTudent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
